version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/code/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
      - PORT=5001
    ports:
      - "5001:5001"
    command: uvicorn main:app --host 0.0.0.0 --port 5001 --reload
